### ISSUE TITLE
improve FPS

### ISSUE THREAD

**Issue by hakS07** [hollance/Inception-CoreML#7]
@hollance 
thanx for the project it was helpful for deeplab real-time segmentation but the capture was very slow even with desiredFrameRate = 30, I tried to improve it to 60 or 240 but i got "libc++abi.dylib: terminating with uncaught exception of type NSException" error .
do you have any idea how can I solve it?
` private func configureSession() {

        guard permissionGranted else { return }

        captureSession.sessionPreset = quality

        guard let captureDevice = selectCaptureDevice() else { return }

               guard let captureDeviceInput = try? AVCaptureDeviceInput(device: captureDevice) else { 
return }     

        guard captureSession.canAddInput(captureDeviceInput) else { return }  
      
       captureSession.addInput(captureDeviceInput)
        do {

            try captureDevice.lockForConfiguration()

            captureDevice.activeVideoMinFrameDuration = CMTimeMake(1, Int32(desiredFrameRate))

            captureDevice.activeVideoMaxFrameDuration = CMTimeMake(1, Int32(desiredFrameRate))

            captureDevice.unlockForConfiguration()
        } catch {print("dd")}

        let videoOutput = AVCaptureVideoDataOutput()

        videoOutput.setSampleBufferDelegate(self, queue: DispatchQueue(label: "sample buffer"))

        guard captureSession.canAddOutput(videoOutput) else { return }

        captureSession.addOutput(videoOutput)

        guard let connection = videoOutput.connection(withMediaType: 

AVFoundation.AVMediaTypeVideo) else { return }

        guard connection.isVideoOrientationSupported else { return }

        guard connection.isVideoMirroringSupported else { return }

        connection.videoOrientation = .portrait

        connection.isVideoMirrored = position == .front
    }`
ios:12.3.1
iphone:6+
xcode:10.1

**Comment by hollance** [comment]
It is not slow because of the FPS but because DeepLab is simply slow.

**Comment by hakS07** [comment]
@hollance ok thank you
